In this part, I would like to clean the data sets I obtained from web scraping. Because I use the same methdology for scrapying different jobs, so the structure for each job is same. I will use the data set containing data analyst jobs as an example to demonstate the cleaning process and do the same thing for other jobs.

In [1]:
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup

In [2]:
data_analyst = pd.read_csv('./data_analyst_scraping.csv') #loading data set

In [3]:
data_analyst.head() #a glimpse at the data set

,Unnamed: 0,Salary Range,Link,Title,Listing Date,Expiry Date,Job Title,Job Teaser,Advertiser,Area,Work Type,Classification,Salary,Salary Type,JD,Location,Job Description,Strong Words
0,0,0-70000,https://www.seek.com.au/job/39582436,Junior Market Research Data Analyst,2019-07-30T00:45:11.000Z,2019-08-29T00:45:11.000Z,Junior Market Research Data Analyst,Project management opportunity for a junior qu...,Ergo Strategy,"CBD, Inner West & Eastern Suburbs",Full Time,Marketing & Communications,"$55,000 - $64,999",AnnualPackage,"<div class=""_2e4Pi2B"" data-automation=""mobileT...",Sydney,About the business Small but mighty â€“ our t...,"['About the business', 'About the role', 'Bene..."
1,1,0-70000,https://www.seek.com.au/job/39666286,Graduate / Junior GIS Analyst,2019-08-09T00:33:51.000Z,2019-09-08T00:33:51.000Z,Graduate / Junior GIS Analyst,Our new Graduate / Junior GIS Analyst will get...,Eco Logical Australia,"CBD, Inner & Western Suburbs",Full Time,Science & Technology,NaN,AnnualPackage,"<div class=""_2e4Pi2B"" data-automation=""mobileT...",Perth,About Us ECO LOGICAL AUSTRALIA PTY LTD is one ...,"['About Us', 'Graduate or Junior\xa0GIS Analys..."
2,2,0-70000,https://www.seek.com.au/job/39756451,Junior Data Analyst,2019-08-21T05:17:35.000Z,2019-09-20T13:59:59.000Z,Junior Data Analyst,Junior Data Analyst needed for a growing Pharm...,Hays Information Technology,North Shore & Northern Beaches,Full Time,Information & Communication Technology,$60000.00 - $70000.00 p.a.,AnnualPackage,"<div class=""_2e4Pi2B"" data-automation=""mobileT...",Sydney,Junior Data Analyst needed for a growing Pharm...,"['Your new company', 'Your new role', ""What yo..."
3,3,0-70000,https://www.seek.com.au/job/39763876,Data Analyst,2019-08-22T02:53:19.000Z,2019-09-21T02:53:19.000Z,Data Analyst,A great opportunity for an enthusiastic data a...,Private Advertiser,"CBD, Inner West & Eastern Suburbs",Full Time,Information & Communication Technology,NaN,AnnualPackage,"<div class=""_2e4Pi2B"" data-automation=""mobileT...",Sydney,The Wine Collective is looking for an up-and-c...,"['About the Role', 'Role requirements', 'About..."
4,4,0-70000,https://www.seek.com.au/job/39755816,Data Analyst / Database Officer,2019-08-21T04:38:06.000Z,2019-09-20T04:38:05.000Z,Data Analyst / Database Officer,A full-time position is available for a Data A...,Douglass Hanly Moir Pathology,Ryde & Macquarie Park,Full Time,Information & Communication Technology,NaN,HourlyRate,"<div class=""_2e4Pi2B"" data-automation=""mobileT...",Sydney,A full-time position is available for a Data A...,[]

Check the 'Job Description', that's where I store my output stright away after extract text from job descriptions

In [4]:
data_analyst['Job Description'][0]

"About the business    Small but mighty â€“ our team is made up of smart people, which you will love learning from every day. We encourage individual passion areas of expertiseWe promote a strong culture of work-life balance, ensuring our people have time to enjoy the things they love outside the officeOur people love to get together for a Friday arvo drink or a long lunch at one of the many amazing restaurants and bars near our office in Rushcutters BayOur gorgeous boutique office is located in Rushcutters Bay, walking distance to buses and Kings Cross station    About the role    What to expect in your first  3 months: Project management including liaising with clients and suppliers, monitoring quotas, fieldwork timelines and the delivery of datafiles from suppliersData manipulation, cleaning and processing, including merging and restructuring files, weighting results, constructing data variables, preparing data file for analysis in Q and Excel data tables for clientsSupporting the team and clients with efficient ways to present data by charting and creating dashboardsDelivering client engagements to a consistently high standard of accuracy Within 6 months: Identifying opportunities for automation within tracking studies and implementing the solutionsAnalysis and interpretation of data to help develop compelling consumer insights presentations and support reporting 12 months and beyond: A data expert in the company, the go to person for combining secondary data with survey data, dashboard solutions, data architecture and automation    Benefits and perks    Collaborate with senior decision-makers at some of Australia's leading blue-chip companies in consumer goods, retail and services to solve challenging business problemsGain exposure to a range of strategic consulting and consumer insights projects â€“ we're as thoughtful about the projects we take on as we are about the people we work withOngoing training and support through industry conferences, topic-specific training courses and our annual off-site (we've been as far as Amsterdam and Istanbul and, closer to home, Bowral, the Blue Mountains and Killcare)    Skills and experience    Must haves Relevant university qualification, demonstrating merit1-2 years' experience in Market Research, with panel provider / research agencyExcellent attention to detail â€“ high quality standards regarding data qualityCommercial thinking and a strong business acumen â€“ ability to think strategicallyExperience in market research analysis, skills in Q or SPSS Nice to haves Programming languages such as R, SAS, SQL, PYTHON, SPSS SyntaxDashboarding solutions such as Tableau, DisplayrMarketing science - segmentation, drivers, modellingMarket research platforms such as Medallia and QualtricsSoftware we regularly use â€“ Excel, Powerpoint, Mekko Graphics, Q, Tableau   "

That seems not correct because some of the words stick to each other, e.g., 'expertiseWe'. Luckily, I keep the raw material in column "JD".

In [5]:
data_analyst = data_analyst.drop(columns=['Job Description'])

In [6]:
data_analyst['JD'][0] #check 'JD' column

'<div class="_2e4Pi2B" data-automation="mobileTemplate"><p><strong>About the business</strong></p> <p>\xa0</p> <ul><li>Small but mighty â€“ our team is made up of smart people, which you will love learning from every day. We encourage individual passion areas of expertise</li><li>We promote a strong culture of work-life balance, ensuring our people have time to enjoy the things they love outside the office</li><li>Our people love to get together for a Friday arvo drink or a long lunch at one of the many amazing restaurants and bars near our office in Rushcutters Bay</li><li>Our gorgeous boutique office is located in Rushcutters Bay, walking distance to buses and Kings Cross station</li></ul> <p>\xa0</p> <p><strong>About the role</strong></p> <p>\xa0</p> <p>What to expect in your first\xa03 months:</p> <ul><li>Project management including liaising with clients and suppliers, monitoring quotas, fieldwork timelines and the delivery of datafiles from suppliers</li><li>Data manipulation, cleaning and processing, including merging and restructuring files, weighting results, constructing data variables, preparing data file for analysis in Q and Excel data tables for clients</li><li>Supporting the team and clients with efficient ways to present data by charting and creating dashboards</li><li>Delivering client engagements to a consistently high standard of accuracy</li></ul> <p>Within 6 months:</p> <ul><li>Identifying opportunities for automation within tracking studies and implementing the solutions</li><li>Analysis and interpretation of data to help develop compelling consumer insights presentations and support reporting</li></ul> <p>12 months and beyond:</p> <ul><li>A data expert in the company, the go to person for combining secondary data with survey data, dashboard solutions, data architecture and automation</li></ul> <p>\xa0</p> <p><strong>Benefits and perks</strong></p> <p>\xa0</p> <ul><li>Collaborate with senior decision-makers at some of Australia\'s leading blue-chip companies in consumer goods, retail and services to solve challenging business problems</li><li>Gain exposure to a range of strategic consulting and consumer insights projects â€“ we\'re as thoughtful about the projects we take on as we are about the people we work with</li><li>Ongoing training and support through industry conferences, topic-specific training courses and our annual off-site (we\'ve been as far as Amsterdam and Istanbul and, closer to home, Bowral, the Blue Mountains and Killcare)</li></ul> <p>\xa0</p> <p><strong>Skills and experience</strong></p> <p>\xa0</p> <p><strong>Must haves</strong></p> <ul><li>Relevant university qualification, demonstrating merit</li><li>1-2 years\' experience in Market Research, with panel provider / research agency</li><li>Excellent attention to detail â€“ high quality standards regarding data quality</li><li>Commercial thinking and a strong business acumen â€“ ability to think strategically</li><li>Experience in market research analysis, skills in Q or SPSS</li></ul> <p><strong>Nice to haves</strong></p> <ul><li>Programming languages such as R, SAS, SQL, PYTHON, SPSS Syntax</li><li>Dashboarding solutions such as Tableau, Displayr</li><li>Marketing science - segmentation, drivers, modelling</li><li>Market research platforms such as Medallia and Qualtrics</li><li>Software we regularly use â€“ Excel, Powerpoint, Mekko Graphics, Q, Tableau</li></ul> <p>\xa0</p></div>'

In [7]:
#try to feed the raw material into BeautifulSoup and check the result
r = data_analyst['JD'][0]
Soup = BeautifulSoup(r, 'html')
test_JD = Soup.get_text(separator=" ", strip=True)

In [8]:
test_JD

"About the business Small but mighty â€“ our team is made up of smart people, which you will love learning from every day. We encourage individual passion areas of expertise We promote a strong culture of work-life balance, ensuring our people have time to enjoy the things they love outside the office Our people love to get together for a Friday arvo drink or a long lunch at one of the many amazing restaurants and bars near our office in Rushcutters Bay Our gorgeous boutique office is located in Rushcutters Bay, walking distance to buses and Kings Cross station About the role What to expect in your first\xa03 months: Project management including liaising with clients and suppliers, monitoring quotas, fieldwork timelines and the delivery of datafiles from suppliers Data manipulation, cleaning and processing, including merging and restructuring files, weighting results, constructing data variables, preparing data file for analysis in Q and Excel data tables for clients Supporting the team and clients with efficient ways to present data by charting and creating dashboards Delivering client engagements to a consistently high standard of accuracy Within 6 months: Identifying opportunities for automation within tracking studies and implementing the solutions Analysis and interpretation of data to help develop compelling consumer insights presentations and support reporting 12 months and beyond: A data expert in the company, the go to person for combining secondary data with survey data, dashboard solutions, data architecture and automation Benefits and perks Collaborate with senior decision-makers at some of Australia's leading blue-chip companies in consumer goods, retail and services to solve challenging business problems Gain exposure to a range of strategic consulting and consumer insights projects â€“ we're as thoughtful about the projects we take on as we are about the people we work with Ongoing training and support through industry conferences, topic-specific training courses and our annual off-site (we've been as far as Amsterdam and Istanbul and, closer to home, Bowral, the Blue Mountains and Killcare) Skills and experience Must haves Relevant university qualification, demonstrating merit 1-2 years' experience in Market Research, with panel provider / research agency Excellent attention to detail â€“ high quality standards regarding data quality Commercial thinking and a strong business acumen â€“ ability to think strategically Experience in market research analysis, skills in Q or SPSS Nice to haves Programming languages such as R, SAS, SQL, PYTHON, SPSS Syntax Dashboarding solutions such as Tableau, Displayr Marketing science - segmentation, drivers, modelling Market research platforms such as Medallia and Qualtrics Software we regularly use â€“ Excel, Powerpoint, Mekko Graphics, Q, Tableau"

This seems much better, except some annoying "\xa03".

In [9]:
#for replacement
import re

def replace(string, substitutions):

    substrings = sorted(substitutions, key=len, reverse=True)
    regex = re.compile('|'.join(map(re.escape, substrings)))
    return regex.sub(lambda match: substitutions[match.group(0)], string)

In [10]:
string = test_JD
repla = {u'\xa0':'  ',u'\xe2\x80\x9d':'  ', u'\n':'  '}
replace(string,repla)

"About the business Small but mighty â€“ our team is made up of smart people, which you will love learning from every day. We encourage individual passion areas of expertise We promote a strong culture of work-life balance, ensuring our people have time to enjoy the things they love outside the office Our people love to get together for a Friday arvo drink or a long lunch at one of the many amazing restaurants and bars near our office in Rushcutters Bay Our gorgeous boutique office is located in Rushcutters Bay, walking distance to buses and Kings Cross station About the role What to expect in your first  3 months: Project management including liaising with clients and suppliers, monitoring quotas, fieldwork timelines and the delivery of datafiles from suppliers Data manipulation, cleaning and processing, including merging and restructuring files, weighting results, constructing data variables, preparing data file for analysis in Q and Excel data tables for clients Supporting the team and clients with efficient ways to present data by charting and creating dashboards Delivering client engagements to a consistently high standard of accuracy Within 6 months: Identifying opportunities for automation within tracking studies and implementing the solutions Analysis and interpretation of data to help develop compelling consumer insights presentations and support reporting 12 months and beyond: A data expert in the company, the go to person for combining secondary data with survey data, dashboard solutions, data architecture and automation Benefits and perks Collaborate with senior decision-makers at some of Australia's leading blue-chip companies in consumer goods, retail and services to solve challenging business problems Gain exposure to a range of strategic consulting and consumer insights projects â€“ we're as thoughtful about the projects we take on as we are about the people we work with Ongoing training and support through industry conferences, topic-specific training courses and our annual off-site (we've been as far as Amsterdam and Istanbul and, closer to home, Bowral, the Blue Mountains and Killcare) Skills and experience Must haves Relevant university qualification, demonstrating merit 1-2 years' experience in Market Research, with panel provider / research agency Excellent attention to detail â€“ high quality standards regarding data quality Commercial thinking and a strong business acumen â€“ ability to think strategically Experience in market research analysis, skills in Q or SPSS Nice to haves Programming languages such as R, SAS, SQL, PYTHON, SPSS Syntax Dashboarding solutions such as Tableau, Displayr Marketing science - segmentation, drivers, modelling Market research platforms such as Medallia and Qualtrics Software we regularly use â€“ Excel, Powerpoint, Mekko Graphics, Q, Tableau"

This is perfect! No sticking to each other and clean! I'm going to apply this to the rest.

In [11]:
JD = []
for i in data_analyst['JD']:
    try:
        JD.append(replace(BeautifulSoup(i, 'html').get_text(separator=" ", strip=True),repla))
    except:
        JD.append('N/A')
        
data_analyst['Job Description'] = JD

In [12]:
data_analyst.head()

,Unnamed: 0,Salary Range,Link,Title,Listing Date,Expiry Date,Job Title,Job Teaser,Advertiser,Area,Work Type,Classification,Salary,Salary Type,JD,Location,Strong Words,Job Description
0,0,0-70000,https://www.seek.com.au/job/39582436,Junior Market Research Data Analyst,2019-07-30T00:45:11.000Z,2019-08-29T00:45:11.000Z,Junior Market Research Data Analyst,Project management opportunity for a junior qu...,Ergo Strategy,"CBD, Inner West & Eastern Suburbs",Full Time,Marketing & Communications,"$55,000 - $64,999",AnnualPackage,"<div class=""_2e4Pi2B"" data-automation=""mobileT...",Sydney,"['About the business', 'About the role', 'Bene...",About the business Small but mighty â€“ our team...
1,1,0-70000,https://www.seek.com.au/job/39666286,Graduate / Junior GIS Analyst,2019-08-09T00:33:51.000Z,2019-09-08T00:33:51.000Z,Graduate / Junior GIS Analyst,Our new Graduate / Junior GIS Analyst will get...,Eco Logical Australia,"CBD, Inner & Western Suburbs",Full Time,Science & Technology,NaN,AnnualPackage,"<div class=""_2e4Pi2B"" data-automation=""mobileT...",Perth,"['About Us', 'Graduate or Junior\xa0GIS Analys...",About Us ECO LOGICAL AUSTRALIA PTY LTD is one ...
2,2,0-70000,https://www.seek.com.au/job/39756451,Junior Data Analyst,2019-08-21T05:17:35.000Z,2019-09-20T13:59:59.000Z,Junior Data Analyst,Junior Data Analyst needed for a growing Pharm...,Hays Information Technology,North Shore & Northern Beaches,Full Time,Information & Communication Technology,$60000.00 - $70000.00 p.a.,AnnualPackage,"<div class=""_2e4Pi2B"" data-automation=""mobileT...",Sydney,"['Your new company', 'Your new role', ""What yo...",Junior Data Analyst needed for a growing Pharm...
3,3,0-70000,https://www.seek.com.au/job/39763876,Data Analyst,2019-08-22T02:53:19.000Z,2019-09-21T02:53:19.000Z,Data Analyst,A great opportunity for an enthusiastic data a...,Private Advertiser,"CBD, Inner West & Eastern Suburbs",Full Time,Information & Communication Technology,NaN,AnnualPackage,"<div class=""_2e4Pi2B"" data-automation=""mobileT...",Sydney,"['About the Role', 'Role requirements', 'About...",The Wine Collective is looking for an up-and-c...
4,4,0-70000,https://www.seek.com.au/job/39755816,Data Analyst / Database Officer,2019-08-21T04:38:06.000Z,2019-09-20T04:38:05.000Z,Data Analyst / Database Officer,A full-time position is available for a Data A...,Douglass Hanly Moir Pathology,Ryde & Macquarie Park,Full Time,Information & Communication Technology,NaN,HourlyRate,"<div class=""_2e4Pi2B"" data-automation=""mobileT...",Sydney,[],A full-time position is available for a Data A...

In [13]:
data_analyst.columns

Index(['Unnamed: 0', 'Salary Range', 'Link', 'Title', 'Listing Date',
       'Expiry Date', 'Job Title', 'Job Teaser', 'Advertiser', 'Area',
       'Work Type', 'Classification', 'Salary', 'Salary Type', 'JD',
       'Location', 'Strong Words', 'Job Description'],
      dtype='object')

I choose to drop the following columns: 'Unnamed: 0','Salary', 'Salary Type','JD'. There are a lot missing values in "Salary", so when I scraped the website, I add the filter "Salary Range". That's why we can drop "Salary" and "Salary Type" here because they cannot provide enough information.

In [14]:
drop_columns = ['Unnamed: 0','Salary', 'Salary Type','JD','Title']
data_analyst = data_analyst.drop(columns=drop_columns)

In [15]:
data_analyst.head()

,Salary Range,Link,Listing Date,Expiry Date,Job Title,Job Teaser,Advertiser,Area,Work Type,Classification,Location,Strong Words,Job Description
0,0-70000,https://www.seek.com.au/job/39582436,2019-07-30T00:45:11.000Z,2019-08-29T00:45:11.000Z,Junior Market Research Data Analyst,Project management opportunity for a junior qu...,Ergo Strategy,"CBD, Inner West & Eastern Suburbs",Full Time,Marketing & Communications,Sydney,"['About the business', 'About the role', 'Bene...",About the business Small but mighty â€“ our team...
1,0-70000,https://www.seek.com.au/job/39666286,2019-08-09T00:33:51.000Z,2019-09-08T00:33:51.000Z,Graduate / Junior GIS Analyst,Our new Graduate / Junior GIS Analyst will get...,Eco Logical Australia,"CBD, Inner & Western Suburbs",Full Time,Science & Technology,Perth,"['About Us', 'Graduate or Junior\xa0GIS Analys...",About Us ECO LOGICAL AUSTRALIA PTY LTD is one ...
2,0-70000,https://www.seek.com.au/job/39756451,2019-08-21T05:17:35.000Z,2019-09-20T13:59:59.000Z,Junior Data Analyst,Junior Data Analyst needed for a growing Pharm...,Hays Information Technology,North Shore & Northern Beaches,Full Time,Information & Communication Technology,Sydney,"['Your new company', 'Your new role', ""What yo...",Junior Data Analyst needed for a growing Pharm...
3,0-70000,https://www.seek.com.au/job/39763876,2019-08-22T02:53:19.000Z,2019-09-21T02:53:19.000Z,Data Analyst,A great opportunity for an enthusiastic data a...,Private Advertiser,"CBD, Inner West & Eastern Suburbs",Full Time,Information & Communication Technology,Sydney,"['About the Role', 'Role requirements', 'About...",The Wine Collective is looking for an up-and-c...
4,0-70000,https://www.seek.com.au/job/39755816,2019-08-21T04:38:06.000Z,2019-09-20T04:38:05.000Z,Data Analyst / Database Officer,A full-time position is available for a Data A...,Douglass Hanly Moir Pathology,Ryde & Macquarie Park,Full Time,Information & Communication Technology,Sydney,[],A full-time position is available for a Data A...

Clean the column "Strong Word".

In [16]:
data_analyst['Strong Words'][0]

"['About the business', 'About the role', 'Benefits and perks', 'Skills and experience', 'Must haves', 'Nice to haves']"

In [17]:
type(data_analyst['Strong Words'][0])

str

In [18]:
strong = []
replacement = {"[":"","]":"","'":"",",":""}
for i in data_analyst['Strong Words']:
    try:
        strong.append(replace(i,replacement))
    except:
        strong.append('N/A')
data_analyst['Strong Words']=strong

In [19]:
data_analyst.head()

,Salary Range,Link,Listing Date,Expiry Date,Job Title,Job Teaser,Advertiser,Area,Work Type,Classification,Location,Strong Words,Job Description
0,0-70000,https://www.seek.com.au/job/39582436,2019-07-30T00:45:11.000Z,2019-08-29T00:45:11.000Z,Junior Market Research Data Analyst,Project management opportunity for a junior qu...,Ergo Strategy,"CBD, Inner West & Eastern Suburbs",Full Time,Marketing & Communications,Sydney,About the business About the role Benefits and...,About the business Small but mighty â€“ our team...
1,0-70000,https://www.seek.com.au/job/39666286,2019-08-09T00:33:51.000Z,2019-09-08T00:33:51.000Z,Graduate / Junior GIS Analyst,Our new Graduate / Junior GIS Analyst will get...,Eco Logical Australia,"CBD, Inner & Western Suburbs",Full Time,Science & Technology,Perth,About Us Graduate or Junior\xa0GIS Analyst Abo...,About Us ECO LOGICAL AUSTRALIA PTY LTD is one ...
2,0-70000,https://www.seek.com.au/job/39756451,2019-08-21T05:17:35.000Z,2019-09-20T13:59:59.000Z,Junior Data Analyst,Junior Data Analyst needed for a growing Pharm...,Hays Information Technology,North Shore & Northern Beaches,Full Time,Information & Communication Technology,Sydney,"Your new company Your new role ""What youll nee...",Junior Data Analyst needed for a growing Pharm...
3,0-70000,https://www.seek.com.au/job/39763876,2019-08-22T02:53:19.000Z,2019-09-21T02:53:19.000Z,Data Analyst,A great opportunity for an enthusiastic data a...,Private Advertiser,"CBD, Inner West & Eastern Suburbs",Full Time,Information & Communication Technology,Sydney,About the Role Role requirements About The WIn...,The Wine Collective is looking for an up-and-c...
4,0-70000,https://www.seek.com.au/job/39755816,2019-08-21T04:38:06.000Z,2019-09-20T04:38:05.000Z,Data Analyst / Database Officer,A full-time position is available for a Data A...,Douglass Hanly Moir Pathology,Ryde & Macquarie Park,Full Time,Information & Communication Technology,Sydney,,A full-time position is available for a Data A...

Now I'm going to filter out the most related data analyst jobs. Because of the recommendation system of Seek.com.au, it will return some relevant jobs like Front End Developer and IT Analyst because in the job descriptions of these jobs also contains the keyword "Data Analyst". I will filter out the most relevant Data Analyst jobs for our analysis later on, which are the ones explicitly contains "Data Analyst" in their titles.

In [20]:
data_analyst = data_analyst[data_analyst['Job Title'].str.contains('Data Analyst') | data_analyst['Job Title'].str.contains('Data Analytics') | data_analyst['Job Title'].str.contains('Statistical Analyst')]

In [21]:
data_analyst.head()

,Salary Range,Link,Listing Date,Expiry Date,Job Title,Job Teaser,Advertiser,Area,Work Type,Classification,Location,Strong Words,Job Description
0,0-70000,https://www.seek.com.au/job/39582436,2019-07-30T00:45:11.000Z,2019-08-29T00:45:11.000Z,Junior Market Research Data Analyst,Project management opportunity for a junior qu...,Ergo Strategy,"CBD, Inner West & Eastern Suburbs",Full Time,Marketing & Communications,Sydney,About the business About the role Benefits and...,About the business Small but mighty â€“ our team...
2,0-70000,https://www.seek.com.au/job/39756451,2019-08-21T05:17:35.000Z,2019-09-20T13:59:59.000Z,Junior Data Analyst,Junior Data Analyst needed for a growing Pharm...,Hays Information Technology,North Shore & Northern Beaches,Full Time,Information & Communication Technology,Sydney,"Your new company Your new role ""What youll nee...",Junior Data Analyst needed for a growing Pharm...
3,0-70000,https://www.seek.com.au/job/39763876,2019-08-22T02:53:19.000Z,2019-09-21T02:53:19.000Z,Data Analyst,A great opportunity for an enthusiastic data a...,Private Advertiser,"CBD, Inner West & Eastern Suburbs",Full Time,Information & Communication Technology,Sydney,About the Role Role requirements About The WIn...,The Wine Collective is looking for an up-and-c...
4,0-70000,https://www.seek.com.au/job/39755816,2019-08-21T04:38:06.000Z,2019-09-20T04:38:05.000Z,Data Analyst / Database Officer,A full-time position is available for a Data A...,Douglass Hanly Moir Pathology,Ryde & Macquarie Park,Full Time,Information & Communication Technology,Sydney,,A full-time position is available for a Data A...
6,0-70000,https://www.seek.com.au/job/39746760,2019-08-20T05:44:29.000Z,2019-09-19T05:44:29.000Z,Data Analyst,The Data Analyst role encompasses analysing th...,Katungul Aboriginal Corporation Community and ...,NaN,Full Time,Healthcare & Medical,"Wollongong, Illawarra & South Coast",REPORTS TO: DIRECT REPORTS: HOURS: CLASSIFICAT...,REPORTS TO: Director Health Services DIRECT RE...

In [22]:
data_analyst['Category'] = 'Data Analyst'

In [23]:
data_analyst.head()

,Salary Range,Link,Listing Date,Expiry Date,Job Title,Job Teaser,Advertiser,Area,Work Type,Classification,Location,Strong Words,Job Description,Category
0,0-70000,https://www.seek.com.au/job/39582436,2019-07-30T00:45:11.000Z,2019-08-29T00:45:11.000Z,Junior Market Research Data Analyst,Project management opportunity for a junior qu...,Ergo Strategy,"CBD, Inner West & Eastern Suburbs",Full Time,Marketing & Communications,Sydney,About the business About the role Benefits and...,About the business Small but mighty â€“ our team...,Data Analyst
2,0-70000,https://www.seek.com.au/job/39756451,2019-08-21T05:17:35.000Z,2019-09-20T13:59:59.000Z,Junior Data Analyst,Junior Data Analyst needed for a growing Pharm...,Hays Information Technology,North Shore & Northern Beaches,Full Time,Information & Communication Technology,Sydney,"Your new company Your new role ""What youll nee...",Junior Data Analyst needed for a growing Pharm...,Data Analyst
3,0-70000,https://www.seek.com.au/job/39763876,2019-08-22T02:53:19.000Z,2019-09-21T02:53:19.000Z,Data Analyst,A great opportunity for an enthusiastic data a...,Private Advertiser,"CBD, Inner West & Eastern Suburbs",Full Time,Information & Communication Technology,Sydney,About the Role Role requirements About The WIn...,The Wine Collective is looking for an up-and-c...,Data Analyst
4,0-70000,https://www.seek.com.au/job/39755816,2019-08-21T04:38:06.000Z,2019-09-20T04:38:05.000Z,Data Analyst / Database Officer,A full-time position is available for a Data A...,Douglass Hanly Moir Pathology,Ryde & Macquarie Park,Full Time,Information & Communication Technology,Sydney,,A full-time position is available for a Data A...,Data Analyst
6,0-70000,https://www.seek.com.au/job/39746760,2019-08-20T05:44:29.000Z,2019-09-19T05:44:29.000Z,Data Analyst,The Data Analyst role encompasses analysing th...,Katungul Aboriginal Corporation Community and ...,NaN,Full Time,Healthcare & Medical,"Wollongong, Illawarra & South Coast",REPORTS TO: DIRECT REPORTS: HOURS: CLASSIFICAT...,REPORTS TO: Director Health Services DIRECT RE...,Data Analyst

That looks good and I will perform the same cleaning process to the other jobs.

In [24]:
data_scientist= pd.read_csv('./data_scientist_scraping.csv') #loading data set
data_scientist = data_scientist.drop(columns=['Job Description'])

JD = []
for i in data_scientist['JD']:
    try:
        JD.append(replace(BeautifulSoup(i, 'html').get_text(separator=" ", strip=True),repla))
    except:
        JD.append('N/A')
        
data_scientist['Job Description']=JD

drop_columns = ['Unnamed: 0','Salary', 'Salary Type','JD','Title']
data_scientist = data_scientist.drop(columns=drop_columns)

strong = []
replacement = {"[":"","]":"","'":"",",":""}
for i in data_scientist['Strong Words']:
    try:
        strong.append(replace(i,replacement))
    except:
        strong.append('N/A')
data_scientist['Strong Words']=strong

data_scientist = data_scientist[data_scientist['Job Title'].str.contains('Data') & data_scientist['Job Title'].str.contains('Scientist')]
data_scientist['Category'] = 'Data Scientist'

In [25]:
data_scientist.tail()

,Salary Range,Link,Listing Date,Expiry Date,Job Title,Job Teaser,Advertiser,Area,Work Type,Classification,Location,Strong Words,Job Description,Category
513,120000-999999,https://www.seek.com.au/job/39548265,2019-07-24T08:32:56.000Z,2019-08-23T13:59:59.000Z,Lead Data Scientist,"Our client, a well known Australian brand is l...",Robert Walters,"CBD, Inner & Western Suburbs",Full Time,Information & Communication Technology,Perth,Responsibilities: Requirements:,This organisation boasts substantial growth wi...,Data Scientist
515,120000-999999,https://www.seek.com.au/job/39554532,2019-07-25T04:32:20.000Z,2019-08-24T04:32:20.000Z,Senior Data Scientist,Are you ready for a leading role influencing t...,Nimble Australia Pty Ltd,CBD & Inner Suburbs,Full Time,Banking & Financial Services,Melbourne,,Do you live and breath data? Do you know your ...,Data Scientist
517,120000-999999,https://www.seek.com.au/job/39546289,2019-07-24T05:48:45.000Z,2019-08-23T13:59:59.000Z,Senior Data Scientist,We are seeking a Senior Data Scientist that is...,Finite Banking & Finance,NaN,Full Time,Banking & Financial Services,Sydney,,We are seeking a Senior Data Scientist that is...,Data Scientist
518,120000-999999,https://www.seek.com.au/job/39530400,2019-07-22T23:10:40.000Z,2019-08-22T13:59:59.000Z,Senior Data Scientist,Looking for Data scientists/Analytical data ex...,Optus,Ryde & Macquarie Park,Full Time,Information & Communication Technology,Sydney,About DSpark The Role What you need to be succ...,About DSpark DSpark was created from a vision ...,Data Scientist
519,120000-999999,https://www.seek.com.au/job/39534780,2019-07-23T04:06:46.000Z,2019-08-22T13:59:59.000Z,Senior Data Scientist,A leading fintech brand is looking for a Senio...,Hydrogen Group Pty Ltd,NaN,Full Time,Information & Communication Technology,Sydney,About our Client: The Role: Experience: About...,About our Client: Our client is one of the mos...,Data Scientist

In [26]:
BI_analyst= pd.read_csv('./BI_scraping.csv') #loading data set
BI_analyst = BI_analyst.drop(columns=['Job Description'])

JD = []
for i in BI_analyst['JD']:
    try:
        JD.append(replace(BeautifulSoup(i, 'html').get_text(separator=" ", strip=True),repla))
    except:
        JD.append('N/A')
        
BI_analyst['Job Description']=JD

drop_columns = ['Unnamed: 0','Salary', 'Salary Type','JD','Title']
BI_analyst = BI_analyst.drop(columns=drop_columns)

strong = []
replacement = {"[":"","]":"","'":"",",":""}
for i in BI_analyst['Strong Words']:
    try:
        strong.append(replace(i,replacement))
    except:
        strong.append('N/A')
BI_analyst['Strong Words']=strong

BI_analyst = BI_analyst[BI_analyst['Job Title'].str.contains('BI') | BI_analyst['Job Title'].str.contains('Business Intelligence')]
BI_analyst['Category'] = 'BI Analyst'

In [27]:
BI_analyst.head()

,Salary Range,Link,Listing Date,Expiry Date,Job Title,Job Teaser,Advertiser,Area,Work Type,Classification,Location,Strong Words,Job Description,Category
0,0-70000,https://www.seek.com.au/job/39734679,2019-08-19T04:12:50.000Z,2019-09-18T04:12:50.000Z,Business Intelligence Developer,The Business Intelligence Developer is respons...,Peoplecare,NaN,Full Time,Information & Communication Technology,"Wollongong, Illawarra & South Coast",ETL/Business Intelligence Developer Essential ...,We are on the hunt for a well-rounded and tale...,BI Analyst
1,0-70000,https://www.seek.com.au/job/39749416,2019-08-20T10:09:26.000Z,2019-09-19T13:59:59.000Z,BI Developer - 6 Month Contract,Contino are a global organisation and one of t...,Contino,NaN,Contract/Temp,Information & Communication Technology,Sydney,Requirements Benefits,Contino are a global organisation and one of t...,BI Analyst
2,0-70000,https://www.seek.com.au/job/39748504,2019-08-20T07:26:07.000Z,2019-09-19T13:59:59.000Z,Business Analyst - BI,provides support for major Works Division prov...,Talent â€“ Winner â€˜Seek Large Recruitment Agency...,"CBD, Inner West & Eastern Suburbs",Contract/Temp,Information & Communication Technology,Sydney,Key Accountabilities Experience Required Word ...,Talent International is working in partnership...,BI Analyst
3,0-70000,https://www.seek.com.au/job/39641568,2019-08-06T05:25:46.000Z,2019-09-05T13:59:59.000Z,Business Intelligence Analyst (BI),"Pegasus is expanding rapidly, our BI Analyst w...",Pegasus Management Pty Ltd,NaN,Full Time,Information & Communication Technology,"Newcastle, Maitland & Hunter",About Pegasus The Pegasus team The Role Key Re...,About Pegasus Pegasus is one of the fastest gr...,BI Analyst
4,0-70000,https://www.seek.com.au/job/39725154,2019-08-16T07:00:11.000Z,2019-09-15T13:59:59.000Z,BI Lead Consultant / Qlikview / Qlik Sense - S...,BI Lead Consultant / Qlikview / Qlik Sense - S...,Nigel Frank International PTY LTD,NaN,Full Time,Information & Communication Technology,Sydney,Experience sought:,Qlikview Consultant / Qlik Sense - Sydney - Co...,BI Analyst

In [28]:
data_engineer= pd.read_csv('./data_engineer_scraping.csv') #loading data set
data_engineer = data_engineer.drop(columns=['Job Description'])

JD = []
for i in data_engineer['JD']:
    try:
        JD.append(replace(BeautifulSoup(i, 'html').get_text(separator=" ", strip=True),repla))
    except:
        JD.append('N/A')
        
data_engineer['Job Description']=JD

drop_columns = ['Unnamed: 0','Salary', 'Salary Type','JD','Title']
data_engineer = data_engineer.drop(columns=drop_columns)

strong = []
replacement = {"[":"","]":"","'":"",",":""}
for i in data_engineer['Strong Words']:
    try:
        strong.append(replace(i,replacement))
    except:
        strong.append('N/A')
data_engineer['Strong Words']=strong

data_engineer = data_engineer[data_engineer['Job Title'].str.contains('Data Engineer')]
data_engineer['Category'] = 'Data Engineer'

In [29]:
data_engineer.head()

,Salary Range,Link,Listing Date,Expiry Date,Job Title,Job Teaser,Advertiser,Area,Work Type,Classification,Location,Strong Words,Job Description,Category
0,0-70000,https://www.seek.com.au/job/39690163,2019-08-13T01:03:32.000Z,2019-09-12T13:59:59.000Z,Junior Data Engineer,Great opportunity for a Junior/Graduate BI dev...,Hudson,NaN,Full Time,Information & Communication Technology,Brisbane,Benefits include: Tim Smith 07 3258 8453,Our client is looking for a Junior/Graduate Bu...,Data Engineer
1,0-70000,https://www.seek.com.au/job/39749280,2019-08-20T09:25:18.000Z,2019-09-19T13:59:59.000Z,Data Engineer - 6 Month Contract,DESCRIPTIONContino are a global organisation a...,Contino,NaN,Contract/Temp,Information & Communication Technology,Sydney,Requirements Qualifications Benefits,DESCRIPTION Contino are a global organisation ...,Data Engineer
2,0-70000,https://www.seek.com.au/job/39663464,2019-08-08T08:45:13.000Z,2019-09-07T13:59:59.000Z,Junior Data Engineer,If you are a self-starter willing to grow your...,Preacta Recruitment,"CBD, Inner West & Eastern Suburbs",Full Time,Information & Communication Technology,Sydney,JUNIOR DATA ENGINEER Job Responsibilities â€“ Ju...,"JUNIOR DATA ENGINEER My client, a data-special...",Data Engineer
3,0-70000,https://www.seek.com.au/job/39661130,2019-08-08T05:29:07.000Z,2019-09-07T13:59:59.000Z,Agile Data Engineer (x2),"High level experience in Agile delivery, Data ...",Talent â€“ Winner â€˜Seek Large Recruitment Agency...,NaN,Full Time,Information & Communication Technology,Perth,Skills Required: Skills Required: Skills Requi...,Iconic WA Company Initial 12-month contract St...,Data Engineer
4,0-70000,https://www.seek.com.au/job/39688588,2019-08-12T23:22:39.000Z,2019-09-12T13:59:59.000Z,Big Data Engineer,One of Australia's leading retail organisation...,FIRESOFT Consulting,"CBD, Inner West & Eastern Suburbs",Full Time,Information & Communication Technology,Sydney,Big Data Engineer About the company About the ...,Big Data Engineer Surry Hills location 6-month...,Data Engineer

In [30]:
print(data_analyst.shape)
print(data_engineer.shape)
print(data_scientist.shape)
print(BI_analyst.shape)

(400, 14)
(231, 14)
(126, 14)
(329, 14)

In [80]:
jobs = pd.concat([data_analyst,data_engineer,data_scientist,BI_analyst],sort=False)

jobs = jobs.drop(columns=['Listing Date','Expiry Date','Area','Work Type'])

In [83]:
jobs = jobs.dropna()

In [85]:
jobs['Location'].unique()

array(['Sydney', 'Wollongong, Illawarra & South Coast', 'Melbourne',
       'Brisbane', 'Adelaide', 'Hobart', 'ACT', 'Perth',
       'Newcastle, Maitland & Hunter', 'Tamworth & North West NSW',
       'South West Coast VIC', 'Toowoomba & Darling Downs',
       'Northern QLD', 'Darwin', 'Bairnsdale & Gippsland', 'Gold Coast',
       'Sunshine Coast', 'Ballarat & Central Highlands'], dtype=object)

In [86]:
jobs['Classification'].unique()

array(['Information & Communication Technology', 'Healthcare & Medical',
       'Banking & Financial Services', 'Accounting',
       'Administration & Office Support',
       'Manufacturing, Transport & Logistics',
       'Marketing & Communications', 'Community Services & Development',
       'Government & Defence', 'Insurance & Superannuation',
       'Human Resources & Recruitment', 'Consulting & Strategy',
       'Education & Training', 'Mining, Resources & Energy',
       'Real Estate & Property', 'Science & Technology', 'Engineering',
       'Sales', 'Design & Architecture', 'CEO & General Management',
       'Sport & Recreation', 'Advertising, Arts & Media'], dtype=object)

In [87]:
jobs.head()

,Salary Range,Link,Job Title,Job Teaser,Advertiser,Classification,Location,Strong Words,Job Description,Category
2,0-70000,https://www.seek.com.au/job/39756451,Junior Data Analyst,Junior Data Analyst needed for a growing Pharm...,Hays Information Technology,Information & Communication Technology,Sydney,"Your new company Your new role ""What youll nee...",Junior Data Analyst needed for a growing Pharm...,Data Analyst
3,0-70000,https://www.seek.com.au/job/39763876,Data Analyst,A great opportunity for an enthusiastic data a...,Private Advertiser,Information & Communication Technology,Sydney,About the Role Role requirements About The WIn...,The Wine Collective is looking for an up-and-c...,Data Analyst
4,0-70000,https://www.seek.com.au/job/39755816,Data Analyst / Database Officer,A full-time position is available for a Data A...,Douglass Hanly Moir Pathology,Information & Communication Technology,Sydney,,A full-time position is available for a Data A...,Data Analyst
6,0-70000,https://www.seek.com.au/job/39746760,Data Analyst,The Data Analyst role encompasses analysing th...,Katungul Aboriginal Corporation Community and ...,Healthcare & Medical,"Wollongong, Illawarra & South Coast",REPORTS TO: DIRECT REPORTS: HOURS: CLASSIFICAT...,REPORTS TO: Director Health Services DIRECT RE...,Data Analyst
7,0-70000,https://www.seek.com.au/job/39753046,Data Analyst,Work for a well renowned local government offe...,Greythorn Experis,Information & Communication Technology,Melbourne,The role: You will be responsible for: Skills:...,Work for a well renowned local government offe...,Data Analyst

In [88]:
jobs.to_csv('jobs.csv',index=False)

In [89]:
pd.read_csv('jobs.csv')

,Salary Range,Link,Job Title,Job Teaser,Advertiser,Classification,Location,Strong Words,Job Description,Category
0,0-70000,https://www.seek.com.au/job/39756451,Junior Data Analyst,Junior Data Analyst needed for a growing Pharm...,Hays Information Technology,Information & Communication Technology,Sydney,"Your new company Your new role ""What youll nee...",Junior Data Analyst needed for a growing Pharm...,Data Analyst
1,0-70000,https://www.seek.com.au/job/39763876,Data Analyst,A great opportunity for an enthusiastic data a...,Private Advertiser,Information & Communication Technology,Sydney,About the Role Role requirements About The WIn...,The Wine Collective is looking for an up-and-c...,Data Analyst
2,0-70000,https://www.seek.com.au/job/39755816,Data Analyst / Database Officer,A full-time position is available for a Data A...,Douglass Hanly Moir Pathology,Information & Communication Technology,Sydney,NaN,A full-time position is available for a Data A...,Data Analyst
3,0-70000,https://www.seek.com.au/job/39746760,Data Analyst,The Data Analyst role encompasses analysing th...,Katungul Aboriginal Corporation Community and ...,Healthcare & Medical,"Wollongong, Illawarra & South Coast",REPORTS TO: DIRECT REPORTS: HOURS: CLASSIFICAT...,REPORTS TO: Director Health Services DIRECT RE...,Data Analyst
4,0-70000,https://www.seek.com.au/job/39753046,Data Analyst,Work for a well renowned local government offe...,Greythorn Experis,Information & Communication Technology,Melbourne,The role: You will be responsible for: Skills:...,Work for a well renowned local government offe...,Data Analyst
5,0-70000,https://www.seek.com.au/job/39764561,Investment Data Analyst (Graduate),Become a key contributor to our Data & Analyti...,Financial Express Australia,Banking & Financial Services,Sydney,NaN,FE Australia is recruiting for a junior invest...,Data Analyst
6,0-70000,https://www.seek.com.au/job/39758527,Data Analyst,"Close to train eastern suburbs, Established ma...",Niche 212,Banking & Financial Services,Sydney,What you will do: Skills and experience:,Work for a well-recognised national Australian...,Data Analyst
7,0-70000,https://www.seek.com.au/job/39733105,Statistical Data Analyst,Seeking a commercially savvy and proven Statis...,Performance Recruit,Accounting,Melbourne,NaN,Our client is a well-established and market le...,Data Analyst
8,0-70000,https://www.seek.com.au/job/39753343,Start your new career as a Data Analyst,Start your career as a consultant data analyst...,The Data School Pty Ltd,Information & Communication Technology,Sydney,Data is exploding data analysts data scientist...,Data is exploding The demand for great data an...,Data Analyst
9,0-70000,https://www.seek.com.au/job/39705880,Junior Data Analyst - North Shore,Join Infomedia's PMO team as a Junior Data Ana...,Infomedia Ltd,Information & Communication Technology,Sydney,data analyst. few years of data analytics expe...,Infomedia are on the hunt for a data analyst. ...,Data Analyst
10,0-70000,https://www.seek.com.au/job/39738973,Research Data Analyst,Seeking an Immediately Available Data Analyst ...,Michael Page Information Technology,Information & Communication Technology,Melbourne,Client Details Description Profile SQL. PowerB...,Seeking an Immediately Available Data Analyst ...,Data Analyst
11,0-70000,https://www.seek.com.au/job/39749412,Data Analyst - 6 Month Contract,Contino are a global organisation and one of t...,Contino,Information & Communication Technology,Sydney,Requirements Benefits,Contino are a global organisation and one of t...,Data Analyst
12,0-70000,https://www.seek.com.au/job/39691008,Junior Data Analyst,Opportunity for Junior Data Analyst to join Ma...,Private Advertiser,Information & Communication Technology,Sydney,NaN,"As a securities exchange, data is at the core...",Data Analyst
13,0-70000,https://www.seek.com.au/job/39739277,Data Analyst,Join a globally leading company on the leading...,VERIFIER AUSTRALIA PTY LTD,Information & Communication Technology,Melbourne,About the business About the role You Are: You...,About the business Verifier is a consumer driv...,Data Analyst
14,0-70000,https://www.seek.com.au/job/39711488,Data Analyst- Digital Tax,The Digital Tax team delivers solutions to hel...,Deloitte,Accounting,Sydney,â€¢ Reimbursements for professional developmentâ€¢...,â€¢ Reimbursements for professional development ...,Data Analyst
15,0-70000,https://www.seek.com.au/job/39689196,Data Analyst Consultant,Naturally analytical? Love statistics? Want to...,Appreciating Recruitment Group,Administration & Office Support,Sydney,About us:,Are you naturally an analytical thinker? Passi...,Data Analyst
16,0-70000,https://www.seek.com.au/job/39722111,BI/Data Analyst,We are on the lookout for motivated BI/Data An...,TEKsystems,Information & Communication Technology,Brisbane,Skills: Benefits: Nanda Prawiro (07) 3295 7421...,We are on the lookout for motivated BI/Data An...,Data Analyst
17,0-70000,https://www.seek.com.au/job/39715563,Data Analyst,Data Analyst\r\nMelbourne\r\n6 Months Contract...,DX Solutions Pty Ltd,Information & Communication Technology,Melbourne,About DX Solutions: About the Opportunity: The...,"About DX Solutions: Established in 2001, Austr...",Data Analyst
18,0-70000,https://www.seek.com.au/job/39719760,Data Analyst,"Undertake data sourcing, preparation, analysis...",Bupa,Banking & Financial Services,Melbourne,Data & Reporting Analyst As the Data & Reporti...,Our Health Services business unit is looking f...,Data Analyst
19,0-70000,https://www.seek.com.au/job/39698373,"Master Data Analyst, Engineering Organisation",Opportunity for a Master Data Analyst to join ...,Programmed Professionals,"Manufacturing, Transport & Logistics",Sydney,Company: Engineering & Maintenance services Ro...,Company: This company is an Australian leader ...,Data Analyst
20,0-70000,https://www.seek.com.au/job/39713902,Data Analyst / Associate Data Scientist,Join a fast paced artificial intelligence and ...,Elula,Information & Communication Technology,Sydney,About Elula and our team About the opportunity...,About Elula and our team Elula is an exciting ...,Data Analyst
21,0-70000,https://www.seek.com.au/job/39689491,Data Analyst,Data analyst required for three month contract...,Hays Information Technology,Information & Communication Technology,Melbourne,"Your new company Your new role ""What youll nee...",Data analyst required for three month contract...,Data Analyst
22,0-70000,https://www.seek.com.au/job/39708791,Data Analyst Opportunity at Engineering Analyt...,We are looking for bright minds to help solve ...,Resolution Systems,Information & Communication Technology,Adelaide,About Us About You Other stuff Our Technology ...,Are you a data scientist or mechanical enginee...,Data Analyst
23,0-70000,https://www.seek.com.au/job/39705561,Data Analyst - Master Data,6 month contract with potential for extension!,Stryker,Information & Communication Technology,Sydney,The Role: Operations Solutions Analyst Master ...,The Role: As Operations Solutions Analyst with...,Data Analyst
24,0-70000,https://www.seek.com.au/job/39682636,Data Analyst - Epidemiologist,"Data Analyst with SAS programming exp, require...",Enterprise IT Resources Pty Ltd,Information & Communication Technology,Sydney,The Company The role Essential Skills & Experi...,"The Company Our client, is dedicated to helpin...",Data Analyst
25,0-70000,https://www.seek.com.au/job/39669995,Data Analyst,6-month contract working as the Data Analyst f...,Robert Half Technology,Information & Communication Technology,Sydney,The Company The Role Your Profile Apply Today,The Company Robert Half has partnered with a l...,Data Analyst
26,0-70000,https://www.seek.com.au/job/39642793,Data Analyst,Permanent Data Analyst role based in Melbourne...,Sharp & Carter Digital and Technology,Information & Communication Technology,Melbourne,About the Role: You will be reasonable for: Ab...,About the Role: An exciting opportunity for a ...,Data Analyst
27,0-70000,https://www.seek.com.au/job/39695041,Client Reporting and Data Analyst,Working with a enthusiastic team to deliver qu...,Transact1 Pty Ltd,Banking & Financial Services,Brisbane,About the business About the role Benefits and...,About the business At Transact1 our mission is...,Data Analyst
28,0-70000,https://www.seek.com.au/job/39668448,"Data Analyst Marketing Research: Brands, Media...","Data Analyst Marketing Research: Brands, Media...",House of Brand Group,Marketing & Communications,Sydney,About the business House of Brand Screen Audie...,About the business House of Brand (houseofbran...,Data Analyst
29,0-70000,https://www.seek.com.au/job/39653490,Data Analyst,"Contribute to the development, implementation ...",SAHMRI,Information & Communication Technology,Adelaide,Full Time 12 Month Contract About the Role Abo...,"Full Time, 12 Month Contract At the South Aust...",Data Analyst
...,...,...,...,...,...,...,...,...,...,...
1046,120000-999999,https://www.seek.com.au/job/39694551,Senior Business Intelligence Consultant,Working with our Dynamics 365 customers to und...,DXC Technology Australia Pty LTD,Information & Communication Technology,Melbourne,NaN,Due to continued growth we require a Senior BI...,BI Analyst
1047,120000-999999,https://www.seek.com.au/job/39608751,BI/Data Engineer,Opportunity to change the data landscape for t...,Think Talent Pty Ltd,Information & Communication Technology,Melbourne,The Organisation The Opportunity Your Background,The Organisation Growing niche financial servi...,BI Analyst
1048,120000-999999,https://www.seek.com.au/job/39579414,BI/Data Warehouse Analyst Programmer,Undertake BI/Data Warehouse Analyst Programmer...,Hays Information Technology,Information & Communication Technology,Brisbane,What you need to do now,Undertake BI/Data Warehouse Analyst Programmer...,BI Analyst
1049,120000-999999,https://www.seek.com.au/job/39690135,BI Consultant Cognos,Leading ERP software development Company wish ...,Private Advertiser,Information & Communication Technology,Sydney,NaN,"Software developer, delivering ERP and Busines...",BI Analyst
1050,120000-999999,https://www.seek.com.au/job/39683111,Senior Business Intelligence Developer - Laing...,Career Opportunity with Laing O'Rourke. Int. E...,Laing O'Rourke Australia Construction Pty Limited,Information & Communication Technology,Melbourne,"""About Laing ORourke"" About the role Key respo...",About Laing O'Rourke Laing O'Rourke is a $6 bi...,BI Analyst
1051,120000-999999,https://www.seek.com.au/job/39595144,MS BI Developer (Power BI),Experienced B.I. Developer with Power BI exper...,Bluefin Resources Pty Limited,Information & Communication Technology,Melbourne,MS BI Developer (Power BI) Microsoft Business ...,MS BI Developer (Power BI) Experienced Busines...,BI Analyst
1052,120000-999999,https://www.seek.com.au/job/39655192,Oracle EDW Datawarehousing /BI Technical Consu...,We need your technical skills to build & Quali...,bk IT Consulting,Information & Communication Technology,Sydney,Datawarehousing concepts. Advanced Oracle SQL ...,This is a contract role based in Sydney or Bri...,BI Analyst
1053,120000-999999,https://www.seek.com.au/job/39711637,AX/ Business Intelligence Systems Analyst,SEEKING AX/ BI SYSTEMS ANALYST TO JOIN LARGE G...,Dynamo Recruitment,Information & Communication Technology,Sydney,NaN,"Our client, a globally known brand, is seeking...",BI Analyst
1054,120000-999999,https://www.seek.com.au/job/39566667,Business Intelligence Specialist,"ETL, DW, BI Specialist",Talent Street,Information & Communication Technology,Brisbane,Have you: Core Skills:,Talent Street are currently seeking a Business...,BI Analyst
1055,120000-999999,https://www.seek.com.au/job/39607702,Power BI Specialist,Are you a bored BI Analyst looking for your ne...,JM Recruiting,Information & Communication Technology,"Newcastle, Maitland & Hunter",NaN,I have a large Newcastle employer in need of a...,BI Analyst
1056,120000-999999,https://www.seek.com.au/job/39579566,Business Intelligence Reports Developer - mult...,Fantastic long-term contract role in QLD Gover...,u&u. Recruitment Partners,Information & Communication Technology,Brisbane,About the Role Key Responsibilities Skills & E...,About the Role As an experienced Microsoft Bus...,BI Analyst
1057,120000-999999,https://www.seek.com.au/job/39643237,BI Test Analyst - Contract - Brisbane CBD,6 months contract plus potential extensions,M&T Resources,Information & Communication Technology,Brisbane,You will be responsible for As the ideal candi...,The Senior BI Test Analyst is responsible for ...,BI Analyst
1058,120000-999999,https://www.seek.com.au/job/39701083,IT Business Intelligence Analyst,A critical business facing and IT enablement r...,L'Oreal Australia,Information & Communication Technology,Melbourne,ABOUT THE JOB ABOUT YOU ABOUT THE PERKS ABOUT ...,ABOUT THE JOB Provide support to Project Manag...,BI Analyst
1059,120000-999999,https://www.seek.com.au/job/39605879,BI Consultant (MSBI),Work as BI Consultant (MS Stack) servicing blu...,PBI Search,Information & Communication Technology,Sydney,NaN,This award-winning Consultancy and MS Gold Par...,BI Analyst
1060,120000-999999,https://www.seek.com.au/job/39546874,Principal BI Consultant,Build and lead a growing Business Intelligence...,SQL Services,Information & Communication Technology,Sydney,About Us About the role Key Selection Criteria...,About Us SQL Services is the leading supplier ...,BI Analyst
1061,120000-999999,https://www.seek.com.au/job/39595888,Power BI Consultant,"Senior Power BI Consultant, integration project",PS&C Group,Information & Communication Technology,Melbourne,Essential Skills and Experience About us Inter...,Our client has an exciting requirement for a P...,BI Analyst
1062,120000-999999,https://www.seek.com.au/job/39632463,Business Intelligence Developer,6 Month contract with a leading Financial Serv...,Recon Solutions,Information & Communication Technology,Brisbane,Major requirements: SQL (SSIS SSAS SSRS) Why a...,We are currently helping our client to grow th...,BI Analyst
1063,120000-999999,https://www.seek.com.au/job/39618932,BI Test Analyst,Seeking experienced BI Test Analysts | Multipl...,Paxus,Information & Communication Technology,Brisbane,Your Key responsibilities will include: You wi...,Senior Test Analyst â€“ Business Intelligence ex...,BI Analyst
1064,120000-999999,https://www.seek.com.au/job/39579078,BI Analyst Programmer - 6m+ contract,Large scale QLD government department looking ...,Michael Page Information Technology,Information & Communication Technology,Brisbane,Client Details Description Profile Job Offer,Large scale QLD government department looking ...,BI Analyst
1065,120000-999999,https://www.seek.com.au/job/39566904,MS BI Consultant,We are seeking a MS BI Consultant with Microso...,Oakton,Information & Communication Technology,Melbourne,About Oakton About the Role Duties of the rol...,About Oakton Oakton is one of Australiaâ€™s lead...,BI Analyst
1066,120000-999999,https://www.seek.com.au/job/39541384,Senior BI Manager - Banking - Hands on senior ...,"Strong BI, data and analytical ability, skills...",Bluefin Resources Pty Limited,Information & Communication Technology,Sydney,Strong analytical ability skills and experienc...,"Strong analytical ability, skills and experien...",BI Analyst
1067,120000-999999,https://www.seek.com.au/job/39537876,Test Coordinator - BI,Software Testing | Business Intelligence | Dat...,Data#3 People Solutions,Information & Communication Technology,Brisbane,Implementing digital system 6 mth contract + E...,Implementing digital system 6 mth contract + E...,BI Analyst
1068,120000-999999,https://www.seek.com.au/job/39557197,Microsoft Business Intelligence Senior to Mana...,Are you passionate about using data and inform...,Altis Consulting,Information & Communication Technology,Melbourne,Why Altis? Altis Consulting About the role Des...,Are you passionate about using data and inform...,BI Analyst
1069,120000-999999,https://www.seek.com.au/job/39531941,Senior Reporting Analyst - Power BI,Nationally recognised industry leader looking ...,Michael Page Information Technology,Information & Communication Technology,Brisbane,Client Details Description Profile Job Offer,Nationally recognised industry leader looking ...,BI Analyst
1070,120000-999999,https://www.seek.com.au/job/39555097,Business Intelligence Analyst - Cognos/Tableau,The role allows flexible working from home arr...,Aurec,Information & Communication Technology,Sydney,The Company: investing heavily world class fle...,The Company: This company is investing heavily...,BI Analyst
1071,120000-999999,https://www.seek.com.au/job/39576650,Lead Business Intelligence Analyst,Make your mark working with the industry leade...,McMillan Shakespeare,Information & Communication Technology,Melbourne,To succeed as a Lead Business Intelligence Ana...,As a result of growth within the business we a...,BI Analyst
1072,120000-999999,https://www.seek.com.au/job/39597045,Data Analyst - Business Intelligence / Data Wa...,Data Analyst - Business Intelligence / Data Wa...,Infinity Pro,Information & Communication Technology,Toowoomba & Darling Downs,Your Benefits: your CV will need to reflect on...,Your Benefits: Immediate Start; Great Rates Po...,BI Analyst
1073,120000-999999,https://www.seek.com.au/job/39579332,BI / Data Warehouse Analyst Programmer,Join this Government organisation leading the ...,Eden Ritchie Recruitment,Information & Communication Technology,Brisbane,Business Intelligence/Data Warehouse Analyst P...,CBD Location Initial 6 month contract $95 - $1...,BI Analyst
1074,120000-999999,https://www.seek.com.au/job/39588897,Business Intelligence DW Analyst Programmer,Great contract for a large government departme...,Finite IT Recruitment Solutions,Information & Communication Technology,Brisbane,The following work will be involved for the po...,Our client is a large government department an...,BI Analyst
1075,120000-999999,https://www.seek.com.au/job/39572211,Oracle Analytics / BI Senior Consultant - Perth,Seeking for a Senior Oracle Analytics / BI Cos...,DXC Technology Australia Pty LTD,Information & Communication Technology,Perth,Role Description Responsibilities: Skills & Ex...,Role Description Are you ready to deliver indu...,BI Analyst